version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${REDDIT_PORT}:${REDDIT_PORT}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      option:
        fluentd-address: 
          localhost: 24224
        tag: service.post

  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USERNAME}/prometheus:latest
    ports:
      - '9090:9090'
    networks:
      - back_net
      - front_net
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
